
spring:
  mail:
    host: ${SMTP-HOST}
    port: 587
    username: ${MAIL-USERNAME}
    password: ${MAIL-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
