
spring:
  config:
    activate:
      on-profile: local

file:
  workspace: 'C:/workspace'

---

spring:
  config:
    activate:
      on-profile: "!local"

file:
  workspace: '/home/deployer/workspace'
