
---

spring:
  config:
    activate:
      on-profile: "!real"

secret:
  system-key: ${DEV_SECRET_TOKEN}

---

spring:
  config:
    activate:
      on-profile: real

secret:
  system-key: ${SECRET_TOKEN}
